### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by rjiang9** [Machine-Learning-for-Medical-Language/ctakes-rest-package#2]
Hi folks, 

I got this Connection error when I run gainst a data using ctakes-rest-package. 

I have a lot of requests to the server (about 600k rows in total, one request for each row ) which UMLs may not like. What's the correct way to do it?  

Thanks

`   raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /ctakes-web-rest/service/analyze (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb73b796c10>: Failed to establish a new connection: [Errno 61] Connection refused'))`

<img width="773" alt="image" src="https://github.com/Machine-Learning-for-Medical-Language/ctakes-rest-package/assets/7293118/e9a92871-6290-4997-afc0-df31e72b839a">

**Comment by tmills** [comment]
1) Are you able to test small numbers of queries manually and see it working to make sure that it's not a network-related issue?
2) Are you sending queries in parallel or in series? If they are sending in sequential order (blocking) there should be no problem, even if there are a lot in a row. This is not using UMLS (NLM) servers for each query, only one time at startup to authorize your credentials.
3) If you are sending in parallel, this container indeed does not have the ability to handle it and behavior is undetermined. I would recommend looking at our other repo (that depends on this one) for a demo of how to parallelize: https://github.com/Machine-Learning-for-Medical-Language/curate-mimic

**Comment by rjiang9** [comment]
Thank you so much for all the info @tmills! I appreciate it for the confirmation on the requests handling. 

It turns out the docker stopped for some reason on my machine. Silly me.

**Comment by tmills** [comment]
OK, everything looks good in the code above. It really depends what you're trying to do. Hope you find it useful, and check out curate-mimic if you have the ability to run multiple containers in parallel, it will be much faster.

**Comment by rjiang9** [comment]
> OK, everything looks good in the code above. It really depends what you're trying to do. Hope you find it useful, and check out curate-mimic if you have the ability to run multiple containers in parallel, it will be much faster.

I will checkout the curate-mimic. Thanks a lot for the projects!!! @tmills
